name: Feature request
description: Sugira uma melhoria
title: 'feat: '
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: |
        > **⚠️ Aviso de Arquivamento:** Este repositório está arquivado e não está mais ativo. Ele permanece público apenas para fins de estudo. Sugestões de melhoria não serão implementadas nem avaliadas.
  - type: textarea
    id: problem
    attributes:
      label: Problema
      description: Qual problema você quer resolver?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposta
      description: Como você imagina a solução?
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternativas consideradas
